name: CI
on: [push]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Tailwind CSS
        run: npm run build:css
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: "./src"
          token: ${{ github.token }}
