name: Deploy to Shopify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy to Shopify
        env:
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_THEME_ID: ${{ vars.SHOPIFY_THEME_ID }}
          SHOPIFY_FLAG_PATH: src
        run: |
          shopify theme push \
            --store=$SHOPIFY_FLAG_STORE \
            --path=$SHOPIFY_FLAG_PATH \
            --theme=$SHOPIFY_THEME_ID
